/**
 * System Log Model
 * Day 6: Central place for meaningful backend actions
 */

// Action types to log
const LOG_ACTION = {
  // KYC actions
  KYC_STARTED: 'KYC_STARTED',
  KYC_PENDING: 'KYC_PENDING',
  KYC_APPROVED: 'KYC_APPROVED',
  KYC_REJECTED: 'KYC_REJECTED',

  // Webhook actions
  WEBHOOK_RECEIVED: 'WEBHOOK_RECEIVED',
  WEBHOOK_SIGNATURE_FAILED: 'WEBHOOK_SIGNATURE_FAILED',
  WEBHOOK_MISSING_APPLICANT_ID: 'WEBHOOK_MISSING_APPLICANT_ID',
  WEBHOOK_USER_NOT_FOUND: 'WEBHOOK_USER_NOT_FOUND',
  WEBHOOK_DUPLICATE: 'WEBHOOK_DUPLICATE',

  // Transaction actions
  TRANSACTION_BLOCKED: 'TRANSACTION_BLOCKED',
  TRANSACTION_BLOCKED_KYC_NOT_APPROVED: 'TRANSACTION_BLOCKED_KYC_NOT_APPROVED',
  TRANSACTION_ALLOWED: 'TRANSACTION_ALLOWED',
  TRANSACTION_CREATED: 'TRANSACTION_CREATED'
};

// Source of the action
const LOG_SOURCE = {
  KYC_SERVICE: 'KYC_SERVICE',
  WEBHOOK_HANDLER: 'WEBHOOK_HANDLER',
  TRANSACTION_SERVICE: 'TRANSACTION_SERVICE',
  AUTH_SERVICE: 'AUTH_SERVICE',
  ADMIN_SERVICE: 'ADMIN_SERVICE'
};

const SystemLog = {
  tableName: 'system_logs',

  fields: {
    id: 'UUID PRIMARY KEY DEFAULT gen_random_uuid()',
    user_id: 'UUID REFERENCES users(id) ON DELETE SET NULL',
    action: 'VARCHAR(100) NOT NULL',
    source: 'VARCHAR(100) NOT NULL',
    metadata: 'JSONB',
    created_at: 'TIMESTAMP DEFAULT NOW()'
  },

  LOG_ACTION,
  LOG_SOURCE
};

module.exports = SystemLog;
